mojotech/helios2

app/javascript/lib/datetime.js

`toLocaleString` will throw an exception if a browser does not have a defined locale. `toLocaleString` is a bit of misuse in this case since we're formatting dates into parts. don't really want to pull in moment just for this so some research into a better option is required.

fix: force locale in toLocaleString in date formatting lib

---

Gemfile
Gemfile.lock
Procfile.development
app/graphql/types/subscription_type.rb
app/javascript/components/widgets/weather/carousel.jsx
app/javascript/components/widgets/weather/panel.jsx
app/javascript/schema.json
app/lib/clients/darksky_client.rb
app/workers/weather_poller_worker.rb
spec/workers/weather_poller_worker_spec.rb

This PR switches the front end weather widget from polling the weather graphql endpoint to receive weather updates via a web socket subscription. A backend worker is added to run every 5 minutes to poll the locations that clients are currently subscribed to.
Caveats:
* Some of the graphql channel still uses class instance variables to store data. This should eventually be switched to redis.
* Poller interval is currently hardcoded to 5 minutes.

Switch to weather subscriptions

---

config/initializers/sidekiq.rb

Configures sidekiq and sidekiq-repeat to connect to redis using the REDIS_URL env variable (used in Heroku).

fix: configure sidekiq to use redis_url env

---

app/javascript/components/time.jsx

Not sure if this is the best solution.  I tried to add a xlarge line-height to the time, but that was still a few pixels higher than the rest of the row.

Align time to the rest of the row

---

app/javascript/components/carousel.jsx

widgets.length -1 was also causing the last widget in the array to
not be displayed

fix: No need to take(ramda) widgets before mapping

---

app/javascript/components/widgets/weather/panel.jsx

notice was breaking out of the view height and causing scroll bars
Before:

fix: reduce dark sky notice margin

---

package.json

It seems that rails webpacker expects dependencies like webpack and
babel presets to be in dependencies versus devDependencies:
https://github.com/rails/webpacker/issues/512

fix: move depenendecies to fix rake assets:precompile

---

app/javascript/components/widgets/numbers/carousel.jsx
app/javascript/components/widgets/numbers/falling-blocks.jsx
app/javascript/components/widgets/numbers/panel.jsx
app/javascript/lib/datetime.js
app/javascript/lib/datetime.test.js
package.json
yarn.lock

- Wrote tests and implemented functions for datetime using date-fns
- The `timeAndDateForTimezone` and `getStartOfWeek` functions don't have tests because CircleCI runs tests at timezone UTC +0, which is different than the local timezone, and this became a problem when `new Date()` was called. I tried specifying timezone as a parameter but this was only ever used for testing purposes.

Convert datetime.js functions to use date-fns for date calculations

---

Gemfile
Gemfile.lock
app/models/daily_event_summary.rb
app/models/event.rb
db/migrate/20190531061410_create_daily_event_summaries.rb
db/schema.rb
lib/tasks/maintain.rake
spec/models/daily_event_summary_spec.rb

Heroku just notified me that we are using ~9,000 rows of the 10,000 row limit on the hobby-dev database. This adds a rake task to archive the events into daily summaries. The task is scoped to events older than the beginning of the week so it should not impact the current week's counts for mojotech by the numbers widget.

feature: add event archiving task maintain:events

---

app/javascript/lib/datetime.js
app/javascript/lib/datetime.test.js

Change `hh` to `h` for time, which was accidentally switched when implementing everything with `date-fns`

fix: remove trailing 0 from time

---

app/assets/images/icons/icon-calendar.svg
app/controllers/web_hooks/slack_controller.rb
app/graphql/types/announcement_type.rb
app/graphql/types/location_type.rb
app/graphql/types/subscription_type.rb
app/javascript/components/widget-controller.jsx
app/javascript/components/widgets/guests/carousel.jsx
app/javascript/components/widgets/guests/index.jsx
app/javascript/components/widgets/guests/panel.jsx
app/javascript/lib/datetime.js
app/javascript/lib/datetime.test.js
app/javascript/schema.json
app/lib/simulate.rb
app/lib/simulate/slack-announcement.json.erb
app/models/announcement.rb
app/models/location.rb
db/migrate/20190517184255_create_announcements.rb
db/schema.rb
lib/tasks/simulate.rake

- Added another route in the controller to handle a message to the Slack bot like "guests: Welcome to Person 1 and Person 2 from Amica on May 23 2019 at 9:30 pm in Providence"
- Made a table in the database to store each announcement's message, people, company, date and time, and location 
- Added the graphql queries to get the announcements to display in real time on the side carousel and the panel

Add Slack announcements 

---

app/models/widget.rb
db/migrate/20190604172236_create_widgets.rb
db/schema.rb
db/seeds.rb

- Backend to store Widgets that will be rendered in the frontend
- Stores: `name` which matches frontend naming, `enabled` flag, `duration_seconds` of the display, `order` of appearance on the side bar
- Scope: `all_in_order` sorted by `order`, and `enabled` which is also sorted by `order`
- Seeds: `Guests`, `Weather`, `Twitter`, `Numbers` in that order

Add widgets table and model

---

app/javascript/components/date.jsx
app/javascript/components/time.jsx

Date and time have a setInterval that previously was not cleared on dismount. This would produce a memory leak if they were dismounted.

fix: intervals now clear

---

.env.local.sample
INTEGRATIONS.md
app/controllers/web_hooks/slack_controller.rb
app/javascript/components/widgets/guests/tab.jsx
app/javascript/lib/datetime.js
app/javascript/lib/datetime.test.js
app/lib/simulate/slack-announcement.json.erb
app/lib/simulate/slack-message.json.erb

- Change simulation templates to match a complete incoming slack event and not just the event parameter.
- Parse incoming message for guests correctly. Was not realizing that when the event is an `app_mention` a first word corresponding to the bot id is added to the text parameter.
- If an announcement that was today but in the past was added it would be appended to the list, so fixed that by adding another datetime function.

Fix Slack announcement bugs

---

app/graphql/types/query_type.rb
spec/graphql/events_spec.rb

The `after` arg was not parsed from javascript (format is `"Mon, 10 Jun 2019 04:00:00 GMT"`) resulting in no events returned on page refresh. This did not cause an issue with pub/sub since those events are assumed "new" (perhaps the wrong assumption) and just added to the current query cache.

fix: parse after string for event date comparison

---

lib/tasks/simulate.rake

Adds `rake simulate:pull_request[COUNT]` and `rake simulate:slack_message[COUNT]`

feature: add count arg to simulate PR/slack

---

app/graphql/types/location_type.rb
app/graphql/types/weather_type.rb
app/javascript/components/widgets/weather/panel.jsx
app/javascript/components/widgets/weather/sunrise-sunset.jsx
app/javascript/schema.json
app/models/location.rb
app/workers/weather_poller_worker.rb
db/schema.rb
schema.graphql
spec/workers/weather_poller_worker_spec.rb

weather is currently published without any location data so it is
invalid graphql to query solarcycles from the weather published event.
the location query in our subscription is causing the endpoint to fail.
major issues:
* our eslint plugin does not detect incorrect fragment
* subscription query failures do not provide an error

fix: move solar cycles into weather

---

Gemfile
Gemfile.lock
app/models/location.rb
app/models/solarcycle.rb
spec/models/location_spec.rb
spec/models/solarcycle_spec.rb

address issue with solarcycle proxy class not working with graphql and limit solarycycles to after yesterday

fix: address issue with solarcycle proxy class not working with graphql and limit solarycycles to after yesterday

---

app/javascript/components/widgets/messages/message.jsx

Message used to rely on margins to center itself, which caused problems, especially
on the guest tab. Now it uses the screen height to center itself.

fix: remove bad Column styling 

---

app/javascript/components/widgets/numbers/falling-blocks.jsx

addBlocks used to end execution when nextBlock returned nothing. Now it
continues to cycle and only create blocks when nextBlock returns something
valid.

fix: blocks fall correctly when count increases

---

app/javascript/components/live-stream.jsx
app/javascript/components/panel-wrapper.jsx
app/javascript/components/side-panel.jsx
app/javascript/components/twitter.jsx
app/javascript/components/widgets/numbers/falling-blocks.jsx
app/javascript/components/widgets/weather/daily-weather.jsx
app/javascript/components/widgets/weather/panel.jsx
app/javascript/components/widgets/weather/sunrise-sunset.jsx

Fixes scrollbar issues surrounding weather, twitter, live-stream and numbers.
Weather panel's scrollbar problems were fixed by properly resizing the panel components so they correctly moved in relation to the screen size. By having a smaller screen size, the components will get closer together to fit, or grow further apart as the screen height increases.
Live-stream and Twitter were getting using Wrapper twice. Those two are currently placeholders, so having them export null seems appropriate.
Numbers was creating a scrollbar with its absolute positioning. Changing its positioning to fixed solves the scrollbar issue.

Scrollbar Fixes

---

app/javascript/components/side-panel.jsx

The side panel now has a transparent background so its elements are still visible even with blocks behind it.

feat: add transparent background

---

app/javascript/components/widgets/numbers/falling-blocks.jsx

The blocks would remain, even if the counts were reset. To account for this, we can refuse to merge with the saved world if the amount of blocks is greater than the count. We also need to reset the state of githubCommit, githubPull and slackMessages to 0, to prevent the saved state from being greater than the count.

fix: remove blocks when counts are reset

---

app/javascript/components/widgets/weather/hourly-temps.jsx

At Ivan's request, I changed the styling for hourly-weather to be a bit bigger and readable, as well as more centered. It looks a lot better now!

improve styling for hourly-weather

---

app/javascript/components/widget-controller.jsx

The tabIndex meant for operating the panel with the arrow keys left an outline surrounding the app. A simple `outline: none` solves this.

Remove Outline

---

app/graphql/types/location_type.rb
app/graphql/types/traffic_cam_type.rb
app/javascript/components/widget-controller.jsx
app/javascript/components/widgets/traffic/index.jsx
app/javascript/components/widgets/traffic/panel.jsx
app/javascript/schema.json
app/models/location.rb
app/models/traffic_cam.rb
db/migrate/20190823182602_create_traffic_cams.rb
db/schema.rb
db/seeds.rb
schema.graphql
spec/models/traffic_cam_spec.rb

There was some desire to see the state of traffic when leaving for the day, so this should help notify people where the heaviest traffic is around Providence. 
This panel only appears after 4pm every day, and will disable itself at 11pm, so it only appears during times it would be helpful. 
The images refresh when the panel is loaded, so they are reasonably up to date for viewing.

Traffic Alerts

---

app/javascript/components/widgets/numbers/ducks.jsx
app/javascript/components/widgets/numbers/falling-blocks.jsx
package.json
yarn.lock

The matterjs world was being serialized as a large javascript object and
compressed with zlib. This switches that serialization to a filtered
array of javascript object properties. The local state of counts is then
inferred from the world when the graphql query is done loading.

fix: switch local state to filtered world prop

---

app/graphql/helios2_schema.rb
app/graphql/types/base_interface.rb
app/graphql/types/location_type.rb
app/graphql/types/widget_collection_type.rb
app/graphql/types/widget_type.rb
app/javascript/schema.json
app/models/location.rb
app/models/widget.rb
db/schema.rb
db/seeds.rb
schema.graphql
spec/models/solarcycle_spec.rb
spec/models/widget_spec.rb

- Created a `Widget` graphql interface to be used in the frontend to do a single query to get all `Weather`, `Guests`, `Numbers` and `Twitter` information for a given location
- Example query and result: 
- Eventually all existing queries in the frontend could be replaced with a single query like this, and some graphql query type definitions might become unnecessary

Update graphql schema for widget querying

---

app/lib/clients/weather_client.rb

`weather_client.rb` was previously reading for `WEATHER_API`, rather than the instructed `WEATHER_API_KEY`

fix: Typo in Weather Client, read ENV for WEATHER_API_KEY

---

package.json
yarn.lock

- Bump eslint-plugin-graphql to 4.0.0

chore: Resolve node-fetch vulnerability

---

app/javascript/components/app.jsx
app/javascript/components/tab-bar.jsx
app/javascript/packs/application.js
app/javascript/styles.js
package.json
yarn.lock

- Resolves (additional) transient dependency of vulnerable node-fetch version
- Updates usage of styled-components to match version 4.0.0

chore: Bump styled-components to 4.0.0

---

package.json
yarn.lock

chore: Resolve node-notifier vulnerability (Bump jest to 26.6.3)

---

app/javascript/components/widgets/weather/moon-phase.jsx

This addresses the moon not using styled components for PR #211, breaking the frontend when rendering

fix: Support styled-components v4 for moon-phase

---

Dockerfile

This gets the docker builds building at least. 
This is a way simpler setup then running things natively, install docker and run `docker-compose up`. Your web service and all dependent services should load and start with a single command.
The trade off is going to be with developer experience when you start making changes. If you have to rebuild the image every time you make a change its going to slow things down a lot.

[fix] update docker node

---

app/graphql/types/traffic_cam_type.rb
app/javascript/components/widgets/traffic/panel.jsx
app/javascript/schema.json
db/migrate/20210527193617_add_feed_format_to_traffic_cams.rb
db/schema.rb
db/seeds.rb
package.json
schema.graphql
yarn.lock

Ticket to add support for Boulder Traffic Cams, id : #178271931
Boulder cams are livestreams, not images as with the Providence cams. This PR adds react hls player library to enable displaying these streams. Also adds a field to the database which determines how to display the feed.
Cams are visible after 4pm and can be viewed by setting the env field for CITY_NAME to "Boulder" - as was the case in viewing cams before.

feat: add Boulder traffic cams

---

.circleci/config.yml

**Ticket description: **
We sometimes forget to dump the graphql schema from rails leaving schema.json in a broken state until future javascript changes. We should catch this automatically with a CircleCI step that runs the schema dump and asserts the schema files were not changed
**Changes: **
Add shell script to check if schema.json is included in git diff

check diff on schema.json

---

app/graphql/types/query_type.rb

Description: Fixes an issue where only primary location location data was being served to the client by providing a proper rails cache key for queried location data.

[fix] location response rails caching error fix

---

app/graphql/types/subscription_type.rb
app/javascript/schema.json
app/workers/sha_poller_worker.rb
schema.graphql
spec/workers/sha_poller_worker_spec.rb

The file included in this PR create a subscription type which updates the GraphQL database, as well as sends a broadcast to subscribed clients with an updated SHA value. The code in this PR is server side only.

feat: server broadcasting to subscribed clients with updated SHA value

---

app/javascript/components/app.jsx
app/javascript/components/version-compare.jsx

This branch consists of the client-side code that queries the GraphQL database for the deployed SHA value broadcasted by the server. The client then makes the comparison of its current SHA value with the updated queried value. This comparison occurs every five minutes per the server's SHA poller worker. If the SHA values are the same, nothing happens. If they are different, then the page reloads to an updated version of Helios 2.

feat: client receives deployed sha value via subscriptions and performs comparison with current sharing for refresh

---

app/javascript/components/app.jsx

**Description**
Passing WidgetController to the `component` prop of Route via an inline function causes unmounting and remounting of the component rather than being updated. Use of the `render` property fixes this issue.
Source: https://reactrouter.com/web/api/Route/component

chore: remove unnecessary remounts of WidgetController on render

---

__mocks__/emptyMock.js
package.json
yarn.lock

**Description**
1. Adds @twitter alias to the testing environment so the twitter Widget can be imported properly
2. Adds the unfetch dependency to emulate fetch in the testing environment
3. Adds react-hls-player alias mapped to a mock import for the testing environment

chore: add helper dependency and aliases to testing environment

---

app/graphql/types/weather_type.rb
app/javascript/schema.json
schema.graphql

The response from openweather API for current weather may have a null value for windGust.  There was an error that mentioned "cannot return null value for null-nullable field" since  our graphql API does not allow a null value in our schema.
https://www.pivotaltracker.com/story/show/178831309

fix null value issue for windGust

---

app/javascript/components/widget-controller.jsx
app/javascript/components/widget-display.jsx
app/javascript/components/widgets/messages/message.jsx

Display an error message "No widget enabled" if a widgets query for a location returns with an empty array of widgets.
https://www.pivotaltracker.com/story/show/178526431

 feat:display an error message when widget is  empty array

---

app/graphql/types/weather_type.rb
app/javascript/schema.json
schema.graphql

Follow-up task into the other nullable fields from openweathermap API. 
https://www.pivotaltracker.com/story/show/178831309

fix:mark null in graphql types for nullable values in the openweather api response

---

app/lib/clients/create_employees.rb
spec/graphql/bamboohr_spec.rb

@bbazyk caught a bug where in the case that there were more than one employees with a birthday that the test for birthdays in `bamboohr_spec.rb` would fail in circleCI. These fixes should resolve this!

fix: failing circleCI tests for bamboohr_spec

---

app/javascript/components/widgets/traffic/panel.jsx

Fix console warning: "Warning: Each child in a list should have a unique "key" prop." for traffic widget panel

fix: added unique key prop for each displayed cam URL

---

app/javascript/components/widget-controller.jsx

This bug is caused because onCompleted callbacks will be called many times . Removing it calls setNewWidgetId once and fixes the issue.

fix : fresh page load does not show weather

---

app/javascript/components/widgets/traffic/panel.jsx

ID: #181116668
The Providence traffic cam page was showing 2 "images from" URLs for http and https. It will only show the https URL from now on.

fix: Remove extra 'images from' URL from cam page

---

app/graphql/types/location_type.rb
app/graphql/types/weather_type.rb
app/javascript/components/date.jsx
app/javascript/components/hocs/with-fragment.test.jsx
app/javascript/components/time-hero.jsx
app/javascript/components/widgets/weather/sunrise-sunset.jsx
app/javascript/schema.json
schema.graphql

The Rails schema had timezone as 1 word and since it's 2 words I switched it to "time_zone" to keep it consistent with other fields.

refactor: make timezone field 2 words

---

app/javascript/components/widgets/numbers/falling-blocks.jsx
app/javascript/components/widgets/numbers/panel.jsx
config/environments/development.rb
lib/tasks/simulate.rake

ID: #181114917
Each serialized block gets a random y position. This causes them to fall from the top each time the slack/github events page mounts.

feat: blocks fall again after cycle

---

app/javascript/components/date.jsx
app/javascript/components/time.jsx
app/javascript/components/widgets/weather/semi-circle.jsx
app/javascript/components/widgets/weather/sunrise-sunset.jsx

The time was defaulting to UTC due to propTypes and prop names using `timezone` instead of `timeZone` on the frontend.

fix: proptypes with incorrect casing of timeZone

---

config/environments/production.rb

Users were getting a CORS error when accessing the HTTP domain. All HTTP requests will now be redirected to HTTPS in production.

fix: force ssl in production

---

server-phoenix/lib/helios/announcement.ex
server-phoenix/lib/helios/location.ex
server-phoenix/lib/helios/traffic_cam.ex
server-phoenix/lib/helios/widget.ex

Ecto.Schema.timestamps automatically fills in 'inserted_at' and 'updated_at' columns. I changed the 'inserted_at' column name to 'created_at' to match the database schema, and the type from default 'naive_datetime' to 'utc_datetime'.

fix: fields to ecto timestamps in schemas

---

app/graphql/types/announcement_type.rb
app/graphql/types/widget_type.rb
app/javascript/schema.json
db/migrate/20220302163416_change_location_id_type_from_announcements.rb
db/schema.rb
schema.graphql

changed "location_id" type from string to integer because it was throwing "ArgumentError" when accessing the location_id from Announcement table from Phoenix.  location_id has to be set to an integer, not a string.

fix: change location id type from announcements

---

server-phoenix/lib/helios_web/schema/resolvers/location.ex

parent is temporarily not being used

chore: temporary fix in day_announcements in location resolvers

---

.gitignore
server-phoenix/.gitignore

- Whenever `mix test` done in cmd, these files are generated in server-phoenix:
- helios_test
- helios_test-shm
- helios_test-wal
- Accidentally added sqlite3 db in server-phoenix gitignore in previous merge with master, so removed it and added it to .gitignore

chore: gitignore updates

---

app/graphql/types/widget_type.rb
app/javascript/components/widgets/numbers/panel.jsx
app/javascript/schema.json
schema.graphql
server-phoenix/lib/helios_web/schema/types/widget.ex

An error was being thrown in the events widget because the frontend and rails side were still using `after` as an argument (to query events) instead of `createdAfter`.

fix: change "after" argument to "created_after"

---

server-phoenix/lib/helios_web/clients/tweet.ex
server-phoenix/test/helios_web/clients/tweet_test.exs

Changes due to tweet object having field `created_at` as type `:datetime` but api response outputs a utc datetime string.

fix: change tweet's created_at format from string to datetime

---

app/javascript/components/app.jsx
server-phoenix/lib/helios_web/clients/weather_client.ex
server-phoenix/lib/helios_web/schema/resolvers/location.ex
server-phoenix/lib/helios_web/schema/resolvers/widget.ex

The weather client was caching a bad response if there was an error with OpenWeatherAPI. 
- Weather will now resolve to a GraphQL error if the response is bad (ex: API key is invalid)
- I also changed ApolloClient's errorPolicy to `none` so the `error` parameter in `useQuery` can be populated with errors. Before it was set to `all`, which renders partial data even if there's an error.
See here for more information: https://www.apollographql.com/docs/react/v2/data/queries/#inspecting-error-states

Fix weather client caching a bad response

---

server-phoenix/lib/mix/tasks/simulate.ex
webpack.config.js

I forgot to update the backend url to `BACKEND_URL` in 2 spots.

fix: incorrect backend env variable

---

server-phoenix/config/config.exs
server-phoenix/lib/helios/application.ex
server-phoenix/lib/helios/workers/weather_poller_worker.ex
server-phoenix/lib/helios_web/AbsintheChannelDecorator.ex
server-phoenix/lib/helios_web/AbsintheSocketDecorator.ex
server-phoenix/lib/helios_web/channel.ex
server-phoenix/lib/helios_web/endpoint.ex
server-phoenix/lib/helios_web/router.ex
server-phoenix/lib/helios_web/schema/types/sub.ex

- Uses Agent to update args of field weather_published. When channel subscribed, the longitude-latitude pair is added to the list of states. When channel unsubscribed, it is removed.
- Implements Absinthe Socket Decorator and Absinthe Channel Decorator, which references code from: [this link](https://github.com/absinthe-graphql/absinthe_phoenix/issues/39#issuecomment-982310059)
- Currently, handle_in("unsubscribe") handles unsubscribing from all channels. Handling unsubscribing from each channel has not been implemented.
- To test out weather poller worker:
- subscribe to weatherPublished using {longitude, latitude} pair in Graphiql
- unsubscribe by exiting out of Graphiql

feat: weather poller worker added

---

app/javascript/components/widgets/weather/sunrise-sunset.jsx

beginTime and endTime had swapped values which caused the sunset and sunrise times and sides to be flipped as well as the moon/sun to be opposite what it should be. Example below.
Before:
After:

Fix for #182249098 bug, involving PVD showing night time during the day

---

.tool-versions

ubuntu has a compilation compatibilty issue with >=24.1.7 and <24.3.3

chore: bump to erlang 24.3.3

---

app/javascript/components/widget-controller.jsx

Page no longer needs to be refreshed if there was an error communicating to the DB, it will try again to refetch the data on error. This also means the webpage can be loaded before the DB server is up, and discover the widgets once DB is alive. Page can also now be opened with all widgets disabled, as enabling a widget after the fact will now work as well. 
Though note that disabling an *active* widget will still require a page refresh.
DB re-check timeout is 5 seconds. (i.e., if there is an error connecting to the DB, Apollo/React will try again every two seconds).

Make Empty and Error pages periodically poll the server to refresh data

---

app/javascript/components/app.jsx
app/javascript/components/bathroom.jsx
app/javascript/components/date.jsx
app/javascript/components/errorLink.test.jsx
app/javascript/components/time-hero.jsx
app/javascript/components/widgets/guests/panel.jsx
app/javascript/components/widgets/numbers/panel.jsx
app/javascript/components/widgets/twitter/panel.jsx
app/javascript/components/wifi.jsx
package.json
yarn.lock

Added console.error statements for wherever errors were being handled in the front end before either `<ErrorMessage/>` or `<DisconnectedMessage/>` was being returned. 
Also added the apollo-link-error dependency for GraphQL error handling (both GraphQL errors and Network errors). Documentation can be found here: https://www.apollographql.com/docs/react/api/link/apollo-link-error/

GraphQL + Frontend error handling

---

cypress/integration/smoke-test-main-page.spec.js
cypress/plugins/index.js
webpack.config.js

This is done so that when we change the FRONTEND_URL in .env, Cypress runs its tests with the new url, and it is also changed for accessing locally (e.g. localhost:5000 to localhost:3000)

chore: Added FRONTEND_URL env var to Cypress and webpack

---

.dockerignore
app/javascript/packs/index.html
esbuild.config.js
package.json

After testing with the backend port, @cbarber realized that there was an issue with Phoenix being able to grab assets. The fix to this is to put `publicPath: '/assets'` into our `esbuild.config.js` file and then restructure where our `index.html` file goes. The backend port should be successfully grabbing those assets now

fix: esbuild backend port not grabbing assets

---

app/javascript/schema.json
schema.graphql
server-phoenix/lib/helios/event.ex
server-phoenix/lib/helios_web/schema/resolvers/event_collection.ex
server-phoenix/lib/helios_web/schema/types/event.ex
server-phoenix/lib/helios_web/schema/types/event_collection.ex
server-phoenix/test/helios_web/schema/resolvers/event_collection_test.exs

_**Edit: See [comment below](https://github.com/mojotech/helios2/pull/403#issuecomment-1156899548)**_
~~The ticket originally called to bale able to run a GraphQL query of approximately the format:~~
```gql
query getTopAuthors {
events(createdAfter: "2022-06-14T14:17:47Z") {
byAuthor(top: 5) {
author
count
}
}
}
```
~~I've instead provided a query that is used like so:~~
```gql
query getTopAuthors {
events(top: 5, createdAfter: "2022-06-14T14:17:47Z") {
byAuthor {
sourceAuthor
count
}
}
}
```
~~The big difference being that the argument is passed to `events()` not to `byAuthor()`. This is due to difficulties with getting the argument in the [`event_collection` resolver](https://github.com/mojotech/helios2/blob/master/server-phoenix/lib/helios_web/schema/resolvers/event_collection.ex). I …

feat: add graphql high-score query

---

app/javascript/components/widgets/weather/current-weather.jsx
app/javascript/components/widgets/weather/current-weather.test.jsx

Added type (rain, snow, sleet, and thunder) to the precipitation description.
Had to pull out the hourly data points to get this, as the minutely data does not contain that level of accuracy. So I'm taking the first hour's precipitation type as the one used in the description of upcoming weather. The start/end of the precipitation is still tracked by the minutely data.

Update projected precipitation to output rain and snow

---

server-phoenix/lib/helios_web/controllers/events_api/events_api_controller.ex
server-phoenix/lib/helios_web/router.ex
server-phoenix/test/helios_web/controllers/events_api/events_api_controller_test.exs

**Endpoint**: `/api/v1/events/{id}`
Sending a POST request here with **body fields**:  `"event_type"` (one of either `"git_commit"` or `"git_pr"`) and `"author"` will add a new row to the DB.
```
POST localhost:4000/api/v1/events/2113728f27ae82c7b1a177c8d03f9e96e0adf246
```
```json
{
"event_type": "git_commit",
"author": "RVRX"
}
```
Will add:
| ... | source  | external_id | ... | source_author|
| -- | ------- | ------------| -- | --------------|
| ... | github_commit | 2113728f27ae82c7b1a177c8d03f9e96e0adf246 | ... | RVRX
The ticket for the PR end of this feature noted that:
> We'll need to come up with some unique id for a branch since this isn't internal to git. Something like sha256(git remote origin + git branch name) may work but would mean we'd need to duplicate the same process in …

Add REST API to create commit and PR events.

---

__mocks__/styleMock.js
app/javascript/components/widgets/twitter/panel.jsx
app/javascript/components/widgets/twitter/tweet.jsx
app/javascript/components/widgets/twitter/tweet_body.jsx
app/javascript/components/widgets/twitter/tweet_content.jsx
app/javascript/components/widgets/twitter/tweet_profile.jsx
app/javascript/components/widgets/twitter/tweet_stats.jsx
package.json
yarn.lock

I was able to display Mojo's tweets in a carousel that is set on a timed interval. All five tweets can be seen before it moves onto the next widget. This is a first draft and there are definitely improvements that can made visually. Any and all feedback would be great!
*Note (things that could be improved on that I noticed so far):
- Making the first tweet (a text tweet) be centered in the carousel 
- Increasing the size of the retweet and favorite icons. Also increasing the opacity of the icons so they can be seen more easily. 
https://user-images.githubusercontent.com/58053105/175128566-efb364c8-8030-426e-a279-dabff25f3659.mov

feat: Added a carousel to display tweets

---

app/javascript/components/get-weather-query.jsx
app/javascript/components/weather-corner.jsx
app/javascript/components/widgets/weather/panel.jsx
app/javascript/schema.json
schema.graphql
server-phoenix/lib/helios_web/AbsintheChannelDecorator.ex
server-phoenix/lib/helios_web/schema/types/sub.ex

Most of the problem lies in `server-phoenix/lib/helios_web/AbsintheChannelDecorator.ex`, with some separate issues lying in `lib/helios_web/schema/types/sub.ex`
Here’s my current understanding of what is happening with the GenServer terminating from our subscriptions:
1. When we switch away from any widget, we run through all of our subscriptions due to our weather poller. For one of our subscriptions, the latitude and longitude values are not available (the weather subscription in this case). 
2. Originally, in the transition from Rails to Phoenix, we made `AbsintheChannelDecorator.ex` to try and get topics with their arguments, as Rails had this capability but Phoenix did not. So, the intention was for these subscriptions to be unsubscribed on page close events, but they are being …

fix: GenServer terminating from GQL subscriptions

---

server-phoenix/lib/helios_web/templates/layout/torch.html.heex

Makes the torch navbar links absolute paths to prevent broken links when in a torch sub-page

Fix torch navbar links

---

app/javascript/components/get-weather-query.jsx
app/javascript/components/widgets/guests/panel.jsx
app/javascript/components/widgets/numbers/panel.jsx
app/javascript/components/widgets/twitter/panel.jsx
app/javascript/components/widgets/weather/weather-effect.jsx
package.json

A typo in prettier was causing it not to be run. Fixed the typo and called prettier:format to update files where prettier had not been run.

fix: typo in prettier

---

server-phoenix/lib/helios_web/controllers/web_hooks/publish_controller.ex

publish_controller (used in simulate.ex for local development) didn't have Event alias and was throwing errors for that reason

adding Event alias
