app/javascript/components/carousel-elements.jsx

feat: Change to consistent WidgetBar

---

app/javascript/components/wifi.jsx

Add wifi password label

---

.env.local.sample
Gemfile
Gemfile.lock
app/controllers/web_hooks/slack_auth_controller.rb
app/controllers/web_hooks/slack_controller.rb
app/javascript/components/widgets/numbers/carousel.jsx
app/javascript/components/widgets/numbers/panel.jsx
app/javascript/lib/datetime.js
app/javascript/lib/datetime.test.js
app/javascript/lib/theme.js
app/lib/simulate.rb
app/lib/simulate/slack-message.json.erb
app/models/event.rb
app/views/web_hooks/slack_auth/new.html.erb
config/routes.rb
lib/tasks/simulate.rake

- Added ruby controller for slack message events to be added to the database
- Added graphql query to count events in the current week and display the number in the panel and carousel
- Added env variables and authentication controller for slack mojotech workspace

slack event numbers

---

INTEGRATIONS.md
README.md

this file will serve as a way to document our integrations with some reasonable start up suggestions for getting up and running for the various API keys and such that will be required for accessing and working on the different widgets.

add INTEGRATIONS.md documentation file

---

app/controllers/web_hooks/github_controller.rb
spec/controllers/web_hooks/github_controller_spec.rb

handle method missing exceptions from github webhook gem

fix: handle method missing exceptions from github webhook gem

---

app/javascript/components/widgets/numbers/carousel.jsx
package.json
yarn.lock

ui(stats): format stat numbers w/ commas

---

app/javascript/components/widgets/numbers/panel.jsx

ui(stats panel): add commas to stat numbers

---

app/controllers/web_hooks/slack_controller.rb

- Make sure only regular messages (with no subtype) and certain subtypes are counted in the numbers. All subtypes can be found here: https://api.slack.com/events/message
- The relevant ones for now are: `file_comment`, `file_mention`, `file_share`, `me_message`, `message_replied`, `thread_broadcast` 
- Tested with rake `simulate:slack_message` where the event would be of a relevant subtype, an irrelevant subtype or would have no subtype

Count only certain Slack message events

---

Dockerfile
docker-compose.yml

Ended up rewriting a lot of the Docker setup. I would still like to figure out how to move the `node_modules` out of the project directory so we don't have to deal with shuffling those packages around in the volume.

Updates to Dockerfile, docker-compose.yml

---

app/javascript/components/fixed-content.jsx
app/javascript/components/time-hero.jsx

This reverts commit 4e09a83211475d6c549413628a00eea31ff967c1.

Revert "Adam's face is the real time hero"

---

app/javascript/components/fixed-content.jsx
app/javascript/components/side-panel.jsx
app/javascript/components/tab-bar.jsx
app/javascript/components/tabs.jsx
app/javascript/components/widget-controller.jsx
app/javascript/components/widgets.jsx

This automatically switches tabs every 20 seconds, but can be stopped by pressing the spacebar. 
I also removed the tabs that were only temporary, as automatically switching to them would be pointless.

Loading Bar to Automatically Switch Tabs

---

app/javascript/components/app.jsx
app/javascript/components/widgets/numbers/ducks.jsx
app/javascript/components/widgets/numbers/falling-blocks.jsx

Fixes: setting correct fetchPolicy for <Query> components
Fixes: falling block initialization (engine was cleared on all component mounts)
Fixes: tearing down world correctly (we did not kill the renderer and runner)

Fix apollo issues

---

app/javascript/components/widgets/numbers/ducks.jsx
package.json
yarn.lock

Cherry picked Will's compress commit in isolation

compress world before storing to local storage

---

app/javascript/components/fixed-content.jsx
app/javascript/components/get-weather-query.jsx
app/javascript/components/side-panel.jsx
app/javascript/components/time-hero.jsx
app/javascript/components/top-corner-controller.jsx
app/javascript/components/weather-corner.jsx
app/javascript/components/widget-controller.jsx
app/javascript/components/widgets/messages/message.jsx
app/javascript/components/widgets/weather/current-percip.jsx
app/javascript/components/widgets/weather/hourly-temps.jsx
app/javascript/components/widgets/weather/panel.jsx

When you aren't on the weather tab, on the right side instead of the time you can now see a small snippet of the weather.
This is handled by the top-corner-controller which selects which view, time or weather, that you should see dependent on the tab.

Right Side Weather View

---

app/javascript/components/widgets/numbers/ducks.jsx
app/javascript/components/widgets/numbers/ducks.test.js
app/javascript/components/widgets/numbers/falling-blocks.jsx

* fixes inflating old data that may be in a browers local storage
* fixes block overlay on first component mount by converting to an onload promise

Fix fallingblock first load

---

app/javascript/components/widgets/weather/hourly-temps.jsx

Shift hourly weather to skip current hour

Shift hourly weathers

---

app/javascript/components/side-panel.jsx
app/javascript/components/widgets/messages/message.jsx
app/javascript/components/widgets/numbers/falling-blocks.jsx
app/javascript/lib/theme.js

Previously message had some weird quirks that ended in it creating large margins where it shouldn't have been.

Fix Message Margins

---

app/javascript/components/widgets/traffic/panel.jsx

Addresses traffic cam image sizing and prop key warning.

Cleanup traffic issues

---

app/javascript/components/widgets/weather/moon-phase.jsx
app/javascript/components/widgets/weather/semi-circle.jsx

Updates PR #184 to support styled-components v4

refactor: Sun and moon path now use arc

---

app/controllers/web_hooks/github_controller.rb
app/controllers/web_hooks/slack_auth_controller.rb
app/controllers/web_hooks/slack_controller.rb
app/lib/app_env.rb
app/lib/clients/twitter_client.rb
app/lib/clients/weather_client.rb

Strips whitespace off of rails environment variables before the rails app initializes.

feat: runtime correction of whitespaces in ENV via proxy AppEnv

---

db/seeds.rb

Added San Diego compatibility for Helios2.

Added San Diego to seeds.rb file

---

README.md

Adds instructions for installing redis, just for ubuntu linux

feat: update README to include ubuntu redis install

---

app/javascript/components/city-name.jsx
app/javascript/components/side-panel.jsx
db/seeds.rb

- app/javascript/components/side-panel.jsx
- app/javascript/components/city-name.jsx
- db/seeds.rb
- This pull request is to display the city name on the application. This component updates each time .env `PRIMARY_CITY_NAME` is changed.
- Replaced 'SanDiego' with 'San Diego'

Added new Javascript component for city name

---

app/graphql/types/tweet_type.rb
app/javascript/components/widgets/twitter/panel.jsx
app/javascript/components/widgets/twitter/tweet_body.jsx
app/javascript/components/widgets/twitter/tweet_content.jsx
app/javascript/schema.json
app/lib/clients/create_tweet.rb
schema.graphql
spec/graphql/tweet_spec.rb

**Ticket Description: **
A console error is displayed when the twitter widget is loaded:
Warning: Each child in a list should have a unique "key" prop.
**Changes: **
Add index & unique key (image path + index) to image wrapper component.

 fix: add unique key for twitter images

---

.env.local.sample
app/graphql/types/location_type.rb
app/javascript/components/wifi.jsx
app/javascript/schema.json
app/models/location.rb
db/migrate/20210527202246_add_env_variables_to_locations.rb
db/schema.rb
db/seeds.rb
schema.graphql

Moved the following env variables into the location record in the database.
*WIFI_NAME
*WIFI_PASSWORD
*BATHROOM_CODE
Also updated seeds.rb to initialize a new database.
https://www.pivotaltracker.com/story/show/178116607

feat:move env variables into the location record in the database

---

README.md

update README to include lint and testing steps

---

app/javascript/components/app.jsx
package.json
yarn.lock

upgrade react to latest version with command: yarn upgrade react@17.0.2 
need to upgrade react in order to upgrade microlink to resolve this error:

upgrade react to latest version

---

db/seeds.rb

The url for Tobey street was broken so it has been replaced with the new url.  https://www.pivotaltracker.com/story/show/178115637

 fix : broken traffic cam

---

.circleci/config.yml

Add step to dumb schema and ensure no changes

add step to dump schema before checking diff

---

.circleci/config.yml
package.json

husky formatter

---

app/controllers/pages_controller.rb
app/graphql/types/query_type.rb
app/javascript/components/app.jsx
app/javascript/components/get-weather-query.jsx
app/javascript/components/side-panel.jsx
app/javascript/components/time-hero.jsx
app/javascript/components/top-corner-controller.jsx
app/javascript/components/weather-corner.jsx
app/javascript/components/widget-controller.jsx
app/javascript/components/widgets/weather/panel.jsx
app/javascript/schema.json
app/models/widget.rb
config/routes.rb
db/seeds.rb
package.json
schema.graphql
yarn.lock

**Description**
1. Adds support for displaying different location _weather_ data based on /<city_name> url query option. Primary Location is still utilized in some components on the frontend for data unrelated to _weather_.
2. Removed obsolete locations from the database.

feat: support displaying location based on the url

---

app/graphql/types/query_type.rb

Description: fixes an error associated with the location query cache key.

[fix] location response rails caching error fix

---

app/javascript/components/widgets/weather/weather-effect.jsx

Designed cloud animation over city image for cloudy weather.
For few clouds:
https://user-images.githubusercontent.com/48374644/122104105-ebf2f700-cddc-11eb-90f8-27e14bbb56fb.mov
For overcast clouds:
https://user-images.githubusercontent.com/48374644/122104136-f57c5f00-cddc-11eb-9417-722822969481.mov
You can see the changes by passing specific values in the "id" for any specific weather day.

feat:design cloud animation

---

app/javascript/components/bathroom.jsx
app/javascript/components/city-name.jsx
app/javascript/components/date.jsx
app/javascript/components/get-weather-query.jsx
app/javascript/components/side-panel.jsx
app/javascript/components/top-corner-controller.jsx
app/javascript/components/weather-corner.jsx
app/javascript/components/widgets/guests/panel.jsx
app/javascript/components/widgets/traffic/panel.jsx
app/javascript/components/widgets/weather/panel.jsx
app/javascript/components/wifi.jsx

**Description**
1. Does away with primaryLocation references on the client side entirely.

chore: fully synchronize components with url location

---

package.json
yarn.lock

Description
I thought unfetch was needed for the testing I am working on, but it isn't.

chore: remove unused unfetch module

---

app/javascript/components/__snapshots__/widget-display.test.jsx.snap
app/javascript/components/widget-controller.jsx
app/javascript/components/widget-display.jsx
app/javascript/components/widget-display.test.jsx
app/javascript/components/widget-transition-controls.jsx
app/javascript/components/widget-transition-controls.test.jsx

1. Adds display components for the WidgetController
2. Refactors WidgetController to follow functional component pattern
3. Adds snapshot tests to assert the WidgetDisplay renders properly for correct input query data
4. Adds tests to assert that the widget transition control state selectors output the correct values given test states

chore: WidgetController refactor

---

app/graphql/types/kelvin_to_farenheit_type.rb
app/graphql/types/weather_type.rb
app/javascript/components/widgets/weather/current-weather.jsx
app/javascript/schema.json
app/lib/clients/weather_client.rb
schema.graphql

Display the information for gusty weather if the wind speed > 15 mph.
Demo of how the gusty wind is displayed:

feat:display information for gusty wind

---

app/javascript/components/widgets/weather/weather-effect.jsx

The cloud speed varies with the wind intensity. The wind speed is  queried from gql and passed it to the duration key inside  cloud which controls the speed of moving cloud.

feat:Sp/vary cloud speed with wind intensity

---

app/graphql/types/user_type.rb
app/models/user.rb
db/migrate/20210712211847_create_users.rb
db/schema.rb

Description
1. Adds users table migration
2. Creates skeleton definition for user graphql type

feat: add users table

---

app/javascript/components/bathroom.jsx
app/javascript/components/date.jsx
app/javascript/components/get-weather-query.jsx
app/javascript/components/hocs/with-fragment.jsx
app/javascript/components/side-panel.jsx
app/javascript/components/time-hero.jsx
app/javascript/components/weather-corner.jsx
app/javascript/components/widget-display.jsx
app/javascript/components/widgets/weather/current-temp.jsx
app/javascript/components/widgets/weather/current-weather.jsx
app/javascript/components/widgets/weather/daily-weather.jsx
app/javascript/components/widgets/weather/hourly-temps.jsx
app/javascript/components/widgets/weather/panel.jsx
app/javascript/components/widgets/weather/sunrise-sunset.jsx
app/javascript/components/widgets/weather/weather-effect.jsx
app/javascript/components/widgets/weather/weather-icon.jsx
app/javascript/components/wifi.jsx

The beginning of rewriting withFragment. First component to work with bathroom.jsx

chore: rewrite withFragment

---

app/graphql/types/employee_event_collection_type.rb
app/graphql/types/employee_type.rb
app/graphql/types/query_type.rb
app/javascript/schema.json
schema.graphql

Adding employees information from bambooHR API to graphql API endpoint

feat: add employees graphql endpoint

---

app/javascript/components/__snapshots__/widget-display.test.jsx.snap
app/javascript/components/get-weather-query.jsx
app/javascript/components/weather-corner.jsx
app/javascript/components/widget-display.jsx
app/javascript/components/widget-display.test.jsx
app/javascript/components/widget-transition-controls.jsx
app/javascript/components/widget-transition-controls.test.jsx
app/javascript/components/widgets/events/panel.jsx
app/javascript/components/widgets/numbers/panel.jsx
app/javascript/components/widgets/traffic/panel.jsx
app/javascript/components/widgets/twitter/panel.jsx
app/javascript/components/widgets/weather/panel.jsx

ticket id #178304916
(This branch was created off of chore: WidgetController refactor #252)

The side panel timer begins before the first widget is loaded

---

app/models/developer_user.rb
db/migrate/20211220181834_developer_users.rb
db/schema.rb

Ticket #180678039
- Adds table migration/model for developer users accommodating slack handle, github handle, and public key

Add a users table for developers

---

.circleci/config.yml
server-phoenix/config/dev.exs
server-phoenix/lib/helios/announcement.ex
server-phoenix/lib/helios/application.ex
server-phoenix/lib/helios/daily_event_summary.ex
server-phoenix/lib/helios/event.ex
server-phoenix/lib/helios/location.ex
server-phoenix/lib/helios/repo.ex
server-phoenix/lib/helios/traffic_cam.ex
server-phoenix/lib/helios/widget.ex
server-phoenix/lib/helios_web/schema/helpers/location.ex
server-phoenix/lib/helios_web/schema/resolvers/event_collection.ex
server-phoenix/lib/helios_web/schema/resolvers/location.ex
server-phoenix/lib/helios_web/schema/resolvers/tweet.ex
server-phoenix/lib/helios_web/schema/resolvers/widget.ex
server-phoenix/lib/helios_web/schema/resolvers/widget_collection.ex
server-phoenix/lib/helios_web/schema/types/location.ex
server-phoenix/lib/helios_web/schema/types/sub.ex
server-phoenix/lib/helios_web/schema/types/weather.ex
server-phoenix/lib/helios_web/schema/types/widget.ex
server-phoenix/priv/repo/seeds.exs

Whenever a PR is merged into master branch, will be dropping the commit, format it, then push it back.

Formatting and checking format in config.yml

---

server-phoenix/lib/helios/location.ex
server-phoenix/lib/helios/widget.ex
server-phoenix/lib/helios_web/schema.ex
server-phoenix/lib/helios_web/schema/helpers/location.ex
server-phoenix/lib/helios_web/schema/helpers/widget_collection.ex
server-phoenix/lib/helios_web/schema/resolvers/location.ex
server-phoenix/lib/helios_web/schema/resolvers/widget_collection.ex
server-phoenix/lib/helios_web/schema/types/location.ex
server-phoenix/lib/helios_web/schema/types/widget.ex
server-phoenix/test/helios_web/schema_test.exs

This is a PR into ll/rb-to-ecto, not master

Added resolvers in Elixir

---

server-phoenix/lib/helios/traffic_cam.ex
server-phoenix/lib/helios_web/schema/resolvers/location.ex

gets all traffic cams for specified location (city_name)

feat: traffic cam resolver added

---

server-phoenix/lib/helios_web/schema/types/tweet.ex
server-phoenix/lib/mix/tasks/simulate.ex
server-phoenix/priv/repo/migrations/20220325165043_add_locations_table.exs
server-phoenix/priv/repo/migrations/20220325165107_add_events_table.exs
server-phoenix/priv/repo/migrations/20220325165154_add_announcements_table.exs
server-phoenix/priv/repo/migrations/20220325180337_add_daily_event_summaries_table.exs
server-phoenix/priv/repo/migrations/20220325180349_add_widgets_table.exs
server-phoenix/priv/repo/migrations/20220325180407_add_traffic_cams_table.exs

Run `mix ecto.reset` to drop the database, run migrations, and seed the data.

Add Ecto migrations

---

.circleci/config.yml
.rubocop.yml
config/database.yml
db/migrate/20220513194158_phoenix_cut_over.rb
db/schema.rb
docker-compose.yml
server-phoenix/config/dev.exs
server-phoenix/config/test.exs
server-phoenix/lib/helios/announcement.ex
server-phoenix/lib/helios/repo.ex
server-phoenix/lib/helios_web/schema/resolvers/location.ex
server-phoenix/mix.exs

This dockerizes redis and postgresql for rails and phoenix. It also include a commit preparing the rails postgresql database for phoenix migrations.

Dockerize redis and postgresql

---

server-phoenix/lib/helios_web/clients/weather_client.ex

Weather client now checks the cache before making an API request.

fix: weather client sending too many api requests

---

.tool-versions
README.md
bin/setup-phx
server-phoenix/README.md
server-phoenix/elixir_buildpack.config
server-phoenix/lib/helios/announcement.ex
server-phoenix/lib/helios/daily_event_summary.ex
server-phoenix/lib/helios/developer_user.ex
server-phoenix/lib/helios/event.ex
server-phoenix/lib/helios/location.ex
server-phoenix/lib/helios/traffic_cam.ex
server-phoenix/lib/helios/user.ex
server-phoenix/lib/helios/widget.ex
server-phoenix/lib/helios_web/schema/helpers/ecto.ex
server-phoenix/phoenix_static_buildpack.config

- adds setup script
- adds changesets to schemas
- forked from [cmb/switch-migrations-to-phoenix](https://github.com/mojotech/helios2/tree/cmb/switch-migrations-to-phoenix)

Standardize Phoenix Setup

---

server-phoenix/lib/helios/slack_channel_names.ex
server-phoenix/test/helios_web/controllers/web_hooks/slack_controller_test.exs

Fixing some compiler warnings on unused variables.

fix: follow compiler lint warnings
